name: Build UEFI for active devices
on:
  push:
    branches: ["main"]
    paths:
      - 'Binaries'
      - 'Common/**'
      - 'Features/**'
      - 'Mu_Basecore'
      - 'MuPatches/**'
      - 'Platforms/**'
      - 'Silicon/**'
      - 'Silicium-ACPI'
  workflow_dispatch:
  inputs:
      download_url:
        description: 'Download URL for UUP dump ZIP file'
        required: true
        type: string
  pull_request:
    types: [opened, reopened]
    paths:
      - 'Binaries'
      - 'Common/**'
      - 'Features/**'
      - 'Mu_Basecore'
      - 'MuPatches/**'
      - 'Platforms/**'
      - 'Silicon/**'
      - 'Silicium-ACPI'
env:
  CI_BUILD: true
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build UEFI for active devices
      
        run: $downloadUrl = "${{ github.event.inputs.download_url }}" && bash ./setup_env.sh -p apt && bash $downloadUrl -d nabu -r DEBUG -c -i

      - name: Upload UEFI images
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images
          path: ./Mu-*
          compression-level: 9
